CREATE TABLE IF NOT EXISTS storages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_type VARCHAR(20)  NOT NULL,
    bucket       VARCHAR(255) NOT NULL,
    path         VARCHAR(255) NOT NULL,
    CONSTRAINT uq_storages_bucket_path UNIQUE (bucket, path)
);

INSERT INTO storages (storage_type, bucket, path) VALUES
    ('STAGING', 'mp3-staging', '/staging'),
    ('PERMANENT', 'mp3-permanent', '/permanent')
ON CONFLICT (bucket, path) DO NOTHING;
