dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'org.apache.tika:tika-core:3.2.2'
    implementation 'org.apache.tika:tika-parser-audiovideo-module:3.0.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
