CREATE TABLE IF NOT EXISTS mp3_resources (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_type VARCHAR(20)  NOT NULL,
    bucket       VARCHAR(255) NOT NULL,
    path         VARCHAR(500) NOT NULL
);
